### PR TITLE
Added `--cpu-profile` config variable

### PR DESCRIPTION
**Pull request by CompuGenius**
This solves #633, plus also helps not having to run the script, encounter the issue, delete all the generated files (because yep, it'll fail if you run it again without doing so), edit the script and run it again 😅
Awesome tool! Currently running the script - it hasn't completed yet but I'm looking forward to a working macOS installation in VirtualBox!

### CODE REVIEW

**Comment by myspaghetti** [comment]
Adding a default profile will most likely break compatibility with more devices than it'll un-break.

**Comment by CompuGenius** [comment]
It can still be added, but commented out by default, no?

**Comment by myspaghetti** [comment]
Would be better with `--cpu-profile host` by default so VBoxManage doesn't throw a fit.

**Comment by CompuGenius** [comment]
Is this better?

**Review by myspaghetti — APPROVED** [review]

**Pull request merged**
