### PR TITLE
Added keyboard docs for MacOS VM.

### PR DESCRIPTION
**Pull request by psjbk**
Added keyboard docs link by Microsoft so that no one opens an issue relating to this in future.

### CODE REVIEW

**Comment by myspaghetti** [comment]
This is not a tutorial on using macOS.

**Comment by psjbk** [comment]
> This is not a tutorial on using macOS.

But you would surely like to avoid any silly issues . And the second thing is that  I'm not adding any tutorials. The link is for someone who would like to know more about keyboard mappings.

**Comment by myspaghetti** [comment]
>But you would surely like to avoid any silly issues.

No, people are free to ask anything they like in the issues and if it's outside of the scope of the project I either say it's outside the scope of the project, or give a short answer, for example issues [243](https://github.com/myspaghetti/macos-virtualbox/issues/243), [244](https://github.com/myspaghetti/macos-virtualbox/issues/244),  [245](https://github.com/myspaghetti/macos-virtualbox/issues/245), and [tens of other questions](https://github.com/myspaghetti/macos-virtualbox/issues?q=label%3Aquestion).

The readme is not the place to answer these questions. The readme should answer the following questions:

- **What is the project?** macos-guest-virtualbox.sh is a Bash script that creates a macOS virtual machine guest on VirtualBox with unmodified macOS installation files downloaded directly from Apple servers
- **What systems does it work on?** Tested on Cygwin. Works on macOS, Windows Subsystem for Linux, and centOS 7. Should work on most modern Linux distros.
- **Where is the documentation?**
- **What features are supported?**
- **What features are not supported?**
- **What are the software dependencies?**

Links to tutorials do not belong on the readme.

**Comment by psjbk** [comment]
Ohk no problem my bad :sad: @myspaghetti

**Pull request closed without merging**
