### PR TITLE
Added link to exporting icloud vars to readme

### PR DESCRIPTION
**Pull request by rbreaves**

### CODE REVIEW

**Comment by myspaghetti** [comment]
I'll add the feature that automatically assigns these variables instead of linking it in the readme.

The `set_variables` function will have an `if False` (or equivalent) that will be commented with something like "change this to `if True` if you want to copy the NVRAM variables required for iMessage from the genuine Mac this script is running on."

**Comment by rbreaves** [comment]
At the moment it appears like the system-id value also does not come on in automatically like every other variable, even when defined in a simple text file in the format that would be expected.

I am going through some old issue tickets right now and finding where the break occurred. I have the nvram bin files generated, so I am just stepping through things right now to get them loaded. As of right now though - my genuine mac values are not working and I am also not using these genuine values currently for icloud/imessage either.

I am not sure what more needs to be added to finish the automation, but I will continue with the documentation here and in my fork until the automation aspects are worked out. Also the iMessageDebug binary is very helpful and imo should be mentioned in the readme.

**Comment by myspaghetti** [comment]
`system-id` is required when using genuine Mac values.

**Comment by rbreaves** [comment]
I know, and that was set in my text file correctly.. but I am hoping that the issue was that I need to either update the vars in the EFI shell as described in the documentation and some issue tickets or I will try and mount the EFI partition and update things there. I don't really care how I have to do it. I don't think adding OpenCore will be needed, but the documentation and/or automation is unclear on this part.

I am not saying the information isn't there at all - it just isn't organized in a manner that helps someone get through this quickly or even somewhat quickly/reasonably fast imo. The rest of your installer is amazingly automated though and I am very impressed.

**Comment by rbreaves** [comment]
Ok, it does appear that booting into the efi shell and letting it do it's thing has helped I think.. because I am getting the vars I am expecting now, although running the ./iMessageDebug binary does not read the values I cared about and will say it'll fail indefinitely.

Instead the comment you had made somewhere else to run these commands to verify that things are set right are the appropriate and only commands one should run.

```
```
system_profiler SPHardwareDataType
ioreg -l | grep -m 1 board-id
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:MLB
nvram 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:ROM
ioreg -l -p IODeviceTree | grep \"system-id
```
```

**Comment by myspaghetti** [comment]
>running the ./iMessageDebug binary does not read the values I cared about and will say it'll fail indefinitely

macOS records the values required to log in to iMessage when you try to log into iMessage for the first time. There are tutorials on the internet for clearing these values from macOS, or if you still have the bootable installer you could delete the virtual machine and start fresh, which might take less time depending considering how unclear (and possibly non-functioning) the tutorials are.

**Comment by rbreaves** [comment]
@myspaghetti Oh everything is running 100% now, the only step that really needs to be mentioned more clearly or automated imo is the pulling of the original/genuine mac values needed, uncommenting the line to pull in that file and that after the initial setup is done to then simply tap Esc and boot into the EFI shell.

A quick 3 step out line like this would have sped things up wonderfully well for me.

Enable iMessage Connectivity
1) Run ./genuine_mac.sh (using what that one user posted)
2) Add file to macos-virtualbox root and uncomment line in .sh setup file to the path of the file.
3) Run installer, reboot into EFI shell after it is completely done by tapping Esc (mention the steps to find the EFI Shell menu option) and let it automatically run startup.nsh.

I mean you could split it up more if you want, but I would have found that digestible compared to having to take several dives on google, and your issue tickets and being uncertain if all the info was even really there to do it or if anything might have changed btwn major releases. My 2015 macbook pro also did not have a value for "DmiOEMVBoxRev", but everything works, so I am happy!

**Pull request closed without merging**
