### PR TITLE
Added older versions of MacOS.

### PR DESCRIPTION
**Pull request by psjbk**
Added Sierra and El Capitan versions of MacOS. Versions older than this can be added but are dead tree versions .

### CODE REVIEW

**Comment by psjbk** [comment]
@myspaghetti It's ready for merging.

**Comment by myspaghetti** [comment]
Doesn't work.

**Comment by psjbk** [comment]
@myspaghetti what's the problem ?

**Comment by myspaghetti** [comment]
If you don't know what's the problem why are you submitting a pull request?

**Comment by psjbk** [comment]
No actually it worked fine on my PC.

**Comment by myspaghetti** [comment]
You don't say. What's the download URL that the script outputs for El Capitan and Sierra?

**Comment by psjbk** [comment]
I don't remember clearly wait I'll have to check.

**Comment by psjbk** [comment]
@myspaghetti I think you'd blocked me.

Now what I was unable to tell you due to block .

I'd forgot to add one change to the script which correctly found the download URL.
But the problem wasn't with the download URL but with the version which got downloaded. When you'd asked me for download URL I didn't had any screenshot or file in which I'd saved the link. So I ran the script for Sierra and went to sleep so that the download got complete. When I woke up I was amazed to find that instead of Sierra it installed High Sierra which was very surprising. I then decided to inspect all the sucatalogs again and compared the download URL with High Sierra and found that they're the same. This is because Apple forcefully pushes the users to install High Sierra or higher only for now. I think when MacOS X 10.16 even the High Sierra sucatalog will meet the same fate.

So ultimately my this pull request also landed to be wrong and I'm really sorry if you think that I'm a mad guy that just keeps on spamming useless pull requests. I only wanted to help you as I love this repo.

**Pull request closed without merging**
