### PR TITLE
Fixed certificate error

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by myspaghetti** [comment]
See issue  #78

**Comment by mickaelandrieu** [comment]
Hi @myspaghetti , my issue wasnt with WSL but with git bash.

Regards

**Comment by myspaghetti** [comment]
Despite its name, `git-bash` is not bash and is not supported by the script.

**Comment by mickaelandrieu** [comment]
Fair enough, thanks for the information !

**Pull request closed without merging**
