### PR TITLE
Made cpu_profile a settable variable.

### PR DESCRIPTION
**Pull request by johnsonjzhou**
Thanks for creating this tool, made a really tedious task very very easy.
On my setup, I keep getting stuck in boot at `[EB|#LOG:EXITBS:START]`.
Assigning a CPU profile addresses this and I thought it would be easier to be able to set this via a variable.
I'm on Windows and using a Comet Lake CPU.

### CODE REVIEW

**Comment by myspaghetti** [comment]
It's kind of a mess I don't want to get into.

There's no documentation for which profiles work with which CPUs, and the [VirtualBox documentation](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm-teleport) refers the user to the CPU architecture documentation. `VBoxManage list hostcpuids` lists the host CPU's CPUIDs but again there's no documentation for any of the leaves and some are architecture-specific.

[QEMU handles CPU features in a much more sensible manner, with each CPU feature being named](https://git.qemu.org/?p=qemu.git;a=blob;f=target/i386/cpu.c) and conflicts with the host CPU are automatically resolved (unless they conflicting settings are explicitly forced). You can see this in practice in [Hayden Barnes's WSL2 nested virtualization project](https://boxofcables.dev/accelerated-kvm-guests-on-wsl-2/) or the [KVM-OpenCore project](https://github.com/Leoyzen/KVM-Opencore/blob/master/libvirt.xml).

VirtualBox doesn't use the `+feature.a -feature.b` syntax, so hardware-independent CPUID settings require parsing the `VBoxManage list hostcpuids` output and filtering out the features that make macOS crash, but I feel like the code that implements this would be longer than the current script (see [QEMU code](https://git.qemu.org/?p=qemu.git;a=blob;f=target/i386/cpu.c)) unless there's a very short list of CPU features that result in a macOS kernel-panic.

Generally, I don't want to blindly apply CPUID settings, but all of these issues _could_ be resolved with enough work.

**Comment by kocoten1992** [comment]
Not sure if this help, but here go https://www.reddit.com/r/hackintosh/comments/g7rqt1/if_youre_stuck_at_endrandomseed_or/

**Comment by myspaghetti** [comment]
Closing pull request until the deeper underlying issues are addressed.

**Comment by johnsonjzhou** [comment]
Apologies for the delayed response.
Thanks for the suggestions and I will take an in depth look at the underlying issues.
Cheers.

**Pull request closed without merging**
